// export const API = {
//   register: "/auth/register",
//   login: "/auth/login",
//   profile: "/auth/profile",
//   tariff: "/tariff",
//   integration: "/integration",
//   // addService: "/add-service",
//   blockchein: "/blockchain",
//   history: "/history/checkaddress",
//   partners: "/partners",
//   team: "/our/team",
//   question: "/FAQ",
//   news: "/news",
//   newsDetail: "/news/detail",
//   services: "/services",
//   servicesDetail: "/services/detail",
//   disabled: "/2fa-disabled",
//   enable: "/2fa-enable",
//   changePassword: "/auth/change-password",
//   delete: "/auth/delete-account",
//   logout: "/auth/logout",
//   forgotPassword: "/auth/forgot-password",
// };

export const API = {
  register: "/auth/register",
  login: "/auth/login",
  profile: "/auth/profile",
  tariff: "/tariff",
  integration: "/integration",
  // addService: "/add-service",
  blockchein: "/blockchain",
  history: "/history/checkaddress",
  checkadress: "/checkaddress/detail",
  partners: "/partners",
  team: "/our/team",
  question: "/FAQ",
  news: "/news",
  newsDetail: "/news/detail",
  services: "/services",
  servicesDetail: "/services/detail",
  disabled: "/2fa-disabled",
  enable: "/2fa-enable",
  changePassword: "/auth/change-password",
  delete: "/auth/delete-account",
  logout: "/auth/logout",
  forgotPassword: "/auth/forgot-password",
  moderation: "/moderation",
  complain: "/complain",
  // rapid: "https://otp-authenticator.p.rapidapi.com",
  // rapidNew: "https://otp-authenticator.p.rapidapi.com/new_v2",
  // rapidenroll: "https://otp-authenticator.p.rapidapi.com/enroll",
  // rapidValidate: "https://otp-authenticator.p.rapidapi.com/validate",
};
