export const API = {
  register: "/auth/register",
  login: "/auth/login",
  profile: "/auth/profile",
  tariff: "/tariff",
  integration: "/integration",
  addService: "/add-service",
  blockchein: "/blockchain",
  history: "/history/checkaddress",
  partners: "/partners",
  team: "/our/team",
  question: "/FAQ",
  news: "/news",
  newsDetail: "/news",
};
