export const API = {
  register: "/auth/register",
  login: "/auth/login",
  profile: "/auth/profile",
  tariff: "/tariff",
  integration: "/integration",
  "add-service": "/add-service",
  blockchein: "/blockchain",
  history: "/history/checkaddress",
  checkadress: "/checkaddress/detail",
  partners: "/partners",
  team: "/our/team",
  question: "/FAQ",
  news: "/news",
  newsDetail: "/news/detail",
  services: "/services",
  servicesDetail: "/services/detail",
  disabled: "/2fa-disabled",
  enable: "/2fa-enable",
  changePassword: "/auth/change-password",
  delete: "/auth/delete-account",
  logout: "/auth/logout",
  forgotPassword: "/auth/forgot-password",
  moderation: "/moderation",
  complain: "/complain",
};
